import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { claimGuardReasons, hardSafetyProblems, scriptQualityProblems, scriptSimilarity, semanticFallbackPlan } from "../src/lib/pawarna/claim-guard";
import { DEFAULT_SETTINGS } from "../src/lib/pawarna/settings";
import type { ContentPlan, JobInput, ProductAnalysis } from "../src/lib/pawarna/types";

const product:ProductAnalysis={name:"Mommy Hana Vitamin C Gummies",brand:"Mommy Hana",category:"vitamin gummy",confidence:"high",visible_text:"Mommy Hana Vitamin C Gummies KIDS Orange Flavour",description:"Bottle",observed_features:["Bekas silinder lutsinar berwarna gelap"],search_query:"",uncertainty:"",reference_indices:[0],variant:"Orange Flavour",primary_function:"suplemen dalam bentuk gummy",product_profile:{productIdentity:"Mommy Hana Vitamin C Gummies",product_identity_source:"physical_packaging",category:"vitamin gummy",primaryFunction:"suplemen dalam bentuk gummy",primary_function_source:"category_knowledge",primary_function_confidence:"medium",targetAudience:"kids",target_audience_source:"physical_packaging",target_audience_confidence:"high",variant:"Orange Flavour",visualIdentityFacts:["Bekas silinder lutsinar berwarna gelap"],salesIntelligenceFacts:["Mommy Hana Vitamin C Gummies","Orange Flavour","suplemen dalam bentuk gummy","kids"],observedFacts:[],listingFacts:[],userFacts:[],productPageFacts:[],safeCategoryFacts:["suplemen dalam bentuk gummy"],unknowns:[],claims:[],confidence:"high",listing_text_detected:false,product_page_fetch_attempted:false,product_page_fetch_status:"not_requested",product_page_identity_match:false,category_knowledge_used:true,micro_question_required:false}};
const plan:ContentPlan={angle:"Problem → Solution",hook:"",script:"",cta:"",mode:"Product Demo",visual_direction:"",claim_evidence_ids:[],video_prompt:"",scene_plan:{"0-2":"a","2-6":"b","6-8":"c","8-10":"d"}};
const problemInput:JobInput={images:["x"],mode:"Auto",instructions:"",angle_seed:"default",settings:{...DEFAULT_SETTINGS,productId:"p",videoStyle:"problem_solution",angle:"problem"}};

test("claim guard rejects invented experience, social proof, promotions, scarcity and efficacy",()=>{for(const text of ["Saya dah guna sendiri","Saya dah cuba","Anak saya suka","Saya repeat","Ramai ibu guna","viral","best seller","ramai puas hati","harga promo","tengah sale","murah sekarang","stok tinggal sikit","cepat sebelum habis","confirm berkesan"])assert.ok(claimGuardReasons(text).length,text);assert.match(hardSafetyProblems({...plan,hook:"Review bagus",script:"Review bagus. Klik link kat bawah."}).join(" "),/attributed/);});
test("sales count cannot be converted into satisfaction",()=>assert.ok(claimGuardReasons("10K satisfied customers").length));
test("safe fallback preserves Problem → Solution and uses semantic facts, not container description",()=>{const result=semanticFallbackPlan(plan,product,problemInput,true);assert.equal(result.angle,"Problem → Solution");assert.match(result.script,/Mommy Hana Vitamin C Gummies/);assert.match(result.script,/suplemen dalam bentuk gummy/);assert.doesNotMatch(result.script,/bekas silinder|berwarna gelap/i);});
test("sales director rejects Dr. Lan generic catalogue copy",()=>{const weak={...plan,hook:"Tengah cari produk penjagaan rambut?",script:"Tengah cari produk penjagaan rambut? Ini Dr. Lan Black Sesame, Black Rice dan Rosemary Water Spray. Klik link kat bawah."};assert.ok(scriptQualityProblems(weak,{...problemInput,settings:{...problemInput.settings!,videoStyle:"problem_solution",angle:"problem"}}).length);});
test("Problem → Solution requires friction and tension while a specific thinning-hair story passes",()=>{const input={...problemInput,settings:{...problemInput.settings!,videoStyle:"problem_solution",angle:"problem"} as typeof problemInput.settings};const generic={...plan,hook:"Kenalkan Dr. Lan",script:"Kenalkan Dr. Lan. Water spray untuk rambut. Klik link kat bawah."},strong={...plan,hook:"Rambut makin nipis sampai belah tengah makin nampak?",script:"Rambut makin nipis sampai belah tengah makin nampak? Jangan buat tak tahu. Dr. Lan untuk penjagaan rambut menipis. Klik link kat bawah sekarang.",cta:"Klik link kat bawah sekarang."};assert.match(scriptQualityProblems(generic,input).join(" "),/friction/);assert.deepEqual(scriptQualityProblems(strong,input),[]);});
test("regenerate rejects an identical hook",()=>assert.match(scriptQualityProblems({...plan,hook:"Hook lama",script:"Hook lama? Produk ini untuk rutin rambut. Klik link kat bawah."},{...problemInput,previous_hook:"Hook lama",settings:{...problemInput.settings!,videoStyle:"real_life",angle:"auto"}}).join(" "),/repeated/));
test("human conversion gate allows general FOMO but hard safety rejects unsupported numbers and unattributed reviews",()=>{const ordinary={...problemInput,settings:{...problemInput.settings!,videoStyle:"real_life",angle:"auto"} as typeof problemInput.settings};assert.deepEqual(scriptQualityProblems({...plan,hook:"Rambut makin jarang?",script:"Rambut makin jarang? Yang ni memang ramai tengah cari. Klik link kat bawah sekarang.",cta:"Klik link kat bawah sekarang."},ordinary),[]);assert.match(scriptQualityProblems({...plan,hook:"Pilihan anda",script:"Produk ini sesuai untuk anda. Klik link kat bawah."},ordinary).join(" "),/formal/);assert.match(hardSafetyProblems({...plan,hook:"Ramai suka",script:"Ramai suka. Dah 10 ribu terjual. Klik link kat bawah."}).join(" "),/numeric/);assert.match(hardSafetyProblems({...plan,hook:"Review menarik",script:"Review menarik. Cepat meresap. Klik link kat bawah."},"review says cepat meresap").join(" "),/attributed/);assert.deepEqual(hardSafetyProblems({...plan,hook:"Ada yang review kata cepat meresap.",script:"Ada yang review kata cepat meresap. Yang ni patut tengok. Klik link kat bawah sekarang.",cta:"Klik link kat bawah sekarang."},"review says cepat meresap"),[]);});
test("recent-script similarity rejects synonym-only regeneration",()=>{const previous="Rambut makin gugur dan jarang? Jangan tunggu makin teruk. Dr Lan untuk rambut menipis. Klik link kat bawah sekarang.";const next="Rambut makin jarang dan gugur? Jangan tunggu makin teruk. Dr Lan untuk rambut menipis. Klik link kat bawah sekarang.";assert.ok(scriptSimilarity(previous,next)>.72);assert.match(scriptQualityProblems({...plan,hook:"Rambut makin jarang dan gugur?",script:next,cta:"Klik link kat bawah sekarang."},{...problemInput,previous_scripts:[previous]}).join(" "),/duplicates/);});
test("creator experience and fake scarcity remain blocked",()=>{for(const text of ["Aku suka sebab senang.","Anak aku guna.","Stok tinggal sikit.","Promo last hari, cepat sebelum habis."])assert.ok(claimGuardReasons(text).length,text);});
test("director prompt makes Auto conversion-first and preserves source semantics",()=>{const source=readFileSync("src/services/pawarna/intelligence.ts","utf8");for(const rule of ["Auto chooses the strongest conversion territory","General non-numeric social-interest FOMO","Review evidence must remain attributed","recent_scripts"] )assert.ok(source.includes(rule),rule);});
