import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { deterministicFinalNormalize, finalDuplicateReasons, openingPattern, sentenceShape, spokenProductName } from "../src/lib/pawarna/final-output";
import { normalizeSpeechBoundary, validSpeech } from "../src/lib/pawarna/speech";
import { spokenMalayCorruptionProblems } from "../src/lib/pawarna/spoken-malay";
import type { ContentPlan, ProductAnalysis } from "../src/lib/pawarna/types";

const product:ProductAnalysis={name:"Dr.Lan BLACK SESAME BLACK RICE & ROSEMARY WATER SPRAY FOR HAIR Natural",brand:"Dr.Lan",category:"hair care",confidence:"high",visible_text:"FOR THINNING HAIR AND HAIR LOSS",description:"spray",observed_features:[],search_query:"",uncertainty:"",reference_indices:[0],primary_function:"penjagaan rambut menipis dan rambut gugur"};
const base:ContentPlan={route_id:"RELATABLE_PAIN",angle:"Problem",hook:"Susah nak cari produk rambut yang senang digunakan?",script:"Susah nak cari produk rambut yang senang digunakan? Dr.Lan BLACK SESAME BLACK RICE & ROSEMARY WATER SPRAY FOR HAIR Natural ni untuk rambut menipis. Klik link kat bawah.",cta:"Klik link kat bawah.",mode:"Product Demo",visual_direction:"product",claim_evidence_ids:[],video_prompt:"",scene_plan:{"0-2":"a","2-6":"b","6-8":"c","8-10":"d"}};

test("deterministic final normalizer shortens long title and preserves route",()=>{const result=deterministicFinalNormalize(base,product);assert.equal(spokenProductName(product),"Dr.Lan");assert.equal(result.route_id,base.route_id);assert.doesNotMatch(result.script,/BLACK SESAME|ROSEMARY WATER SPRAY/i);assert.match(result.script,/Dr\.Lan/);});
test("near paraphrase and repeated opening/shape are hard duplicate signals",()=>{const previous="Susah nak cari produk penjagaan rambut yang mudah digunakan? Dr.Lan Water Spray ni untuk penjagaan rambut yang menipis. Klik link kat bawah.";const next="Susah nak cari produk rambut yang senang digunakan? Dr.Lan Water Spray ni untuk penjagaan rambut yang makin nipis. Klik link kat bawah.";assert.ok(finalDuplicateReasons(next,[previous]).length);assert.equal(openingPattern(next),openingPattern(previous));assert.equal(sentenceShape(next),sentenceShape(previous));});
test("distinct displayed rhythms do not collapse into one opening",()=>{const scripts=["Setiap kali sikat, makin banyak rambut tertinggal? Cuba tengok Dr.Lan ni. Klik link kat bawah.","Geram tengok rambut penuh dekat lantai tiap hari. Cuba tengok spray ni. Klik link kat bawah.","Kalau rambut dah makin jarang, jangan buat tak tahu. Tengok Dr.Lan ni dekat link bawah.","Bila belah tengah dah makin nampak, memang mula risau. Cuba tengok yang ni. Klik link kat bawah.","Kalau tengah survey untuk rambut makin nipis, cuba tengok yang ni. Klik link kat bawah."];assert.ok(new Set(scripts.map(openingPattern)).size>=4);for(let i=1;i<scripts.length;i++)assert.deepEqual(finalDuplicateReasons(scripts[i],scripts.slice(0,i)),[]);});
test("script endpoints enforce fresh attempt, private trace and displayed final equality",()=>{for(const file of ["cloud/products.ts","src/app/api/products/[id]/script/route.ts"]){const source=readFileSync(file,"utf8");for(const token of ["attempt_id=crypto.randomUUID()","outputTrace(plan)","trace.displayed_final!==plan.script","script:trace.displayed_final","Cache-Control"])assert.ok(source.includes(token),`${file}: ${token}`);}});
test("secondary reviewer outage is soft after local hard-safety checks",()=>{const source=readFileSync("src/services/pawarna/intelligence.ts","utf8");assert.ok(source.includes('catch{review={safety_safe:true,quality_approved:false,reason:"Secondary conversion review unavailable; local hard-safety checks passed"}'));});
test("final speech boundary repairs Gemini hook and CTA punctuation deterministically",()=>{const plan=normalizeSpeechBoundary({...base,hook:"Hook lain",script:"Rambut makin gugur? Cuba tengok Dr.Lan ni. Klik link di bawah!",cta:"Klik link di bawah!"});assert.equal(plan.hook,"Rambut makin gugur?");assert.ok(plan.script.endsWith("Klik link kat bawah sekarang."));assert.ok(validSpeech(plan,{voiceoverEnabled:true,voiceStyle:"energetic"} as never));});
test("final boundary treats formal catalogue speech as a rewrite requirement",()=>{const source=readFileSync("src/services/pawarna/intelligence.ts","utf8");assert.ok(source.includes("if(finalNeedsRewrite(plan,product,input))"));});
test("deterministic boundary rewrites the observed Dr Lan catalogue sentence",()=>{const result=deterministicFinalNormalize({...base,script:"Rambut makin nipis? Dr.Lan hadir untuk membantu rutin penjagaan rambut yang menipis dan mudah gugur. Klik link kat bawah."},product);assert.doesNotMatch(result.script,/membantu rutin penjagaan|penjagaan rambut yang menipis/i);assert.match(result.script,/Dr\.Lan ni memang untuk rambut/i);});
test("final surface gate catches Malay catalogue variants",()=>{const source=readFileSync("src/lib/pawarna/final-output.ts","utf8");assert.match(source,/diformulasikan/);});
test("partial packaging-title stacks collapse to the spoken alias without duplicate particles",()=>{const result=deterministicFinalNormalize({...base,script:"Rimas tengok rambut gugur? Dr.Lan Black Sesame Rosemary ni ni memang untuk rambut makin nipis. Klik link kat bawah."},product);assert.doesNotMatch(result.script,/Black Sesame|ni ni/i);assert.match(result.script,/Dr\.Lan ni memang/);});
test("dotted brand rewrite cannot duplicate its prefix",()=>{const result=deterministicFinalNormalize({...base,script:"Risau rambut nipis? Dr.Dr.Lan ni memang untuk rambut yang makin nipis. Klik link kat bawah."},product);assert.doesNotMatch(result.script,/Dr\.Dr\./i);});
test("route-safe fallbacks retain distinct final structures",()=>{const source=readFileSync("src/lib/pawarna/final-output.ts","utf8");assert.ok(source.includes("hairLines:Record<SalesRouteId,string>"));assert.ok(source.includes("Kalau selalu jadi macam ni"));assert.ok(source.includes("Sebelum makin ketara"));});
test("final pipeline order includes normalizer, post-normalizer claim check and hard dedupe",()=>{const source=readFileSync("src/services/pawarna/intelligence.ts","utf8");for(const token of ["FINAL NORMALIZER V1.6","finalSafety=hardSafetyProblems","finalDuplicateReasons","final_normalized_candidate","displayedPlan"])assert.ok(source.includes(token),token);});
test("V1.7 rejects corrupted spoken tokens and runs QA before display",()=>{assert.ok(spokenMalayCorruptionProblems("Cubareit tengok Dr.Lan ni.").length);assert.ok(spokenMalayCorruptionProblems("cuba cuba tengok").length);assert.deepEqual(spokenMalayCorruptionProblems("Cuba tengok Dr.Lan ni."),[]);const source=readFileSync("src/services/pawarna/intelligence.ts","utf8");for(const token of ["FINAL SPOKEN-MALAY QA V1.7","await spokenMalayQA","qaSafety=hardSafetyProblems","post_qa_claim_check"])assert.ok(source.includes(token),token);});
test("V1.7 repairs and detects missing space after a sentence stop",()=>{assert.ok(spokenMalayCorruptionProblems("Lantai penuh rambut.Dr.Lan ni untuk rutin rambut.").length);const result=deterministicFinalNormalize({...base,script:"Lantai penuh rambut.Dr.Lan ni untuk rutin rambut. Klik link kat bawah."},product);assert.match(result.script,/rambut\. Dr\.Lan/);});
test("V1.7 rejects observed awkward recommendation and modal attachment",()=>{assert.ok(spokenMalayCorruptionProblems("Dr.Lan ni memang patut masuk senarai nak tengok.").length,"translated recommendation");assert.ok(spokenMalayCorruptionProblems("Boleh cuba Dr.Lan ni memang untuk rambut nipis.").length,"modal attachment");});
test("V1.7 rejects unnatural hair-routine noun attachment",()=>{assert.ok(spokenMalayCorruptionProblems("Untuk rutin rambut makin nipis, cuba tengok Dr.Lan ni.").length);});
