import test from "node:test";
import assert from "node:assert/strict";
import { resolveProductIntelligence } from "../src/lib/pawarna/product-resolver";
import { applyCorrections, type ProductProject } from "../src/lib/pawarna/projects";
import type { JobInput, ProductAnalysis } from "../src/lib/pawarna/types";

const input:JobInput={images:["front","back"],mode:"Auto",instructions:"",angle_seed:"default"};
const base:ProductAnalysis={name:"Mommy Hana Vitamin C Gummies",brand:"Mommy Hana",category:"vitamin gummies",confidence:"high",visible_text:"Vitamin C Gummies",description:"Compact product packaging",observed_features:["Compact bottle","Orange label"],search_query:"",uncertainty:"",reference_indices:[0,1],physical_product_text:["Mommy Hana","Vitamin C Gummies"],listing_text:["Orange 60pcs"],ui_text:["TikTok PayLater","Buy now"],primary_function:"Belum disahkan",target_audience:"Belum disahkan"};

test("multi-image packaging and listing evidence stay separate from UI",async()=>{const result=await resolveProductIntelligence(base,input),profile=result.product_profile!;assert.deepEqual(result.physical_product_text,["Mommy Hana","Vitamin C Gummies"]);assert.deepEqual(result.listing_text,["Orange 60pcs"]);assert.deepEqual(result.ui_text,["TikTok PayLater","Buy now"]);assert.equal(profile.listing_text_detected,true);assert.ok(profile.claims.some(x=>x.text==="Mommy Hana"&&x.safety==="SAFE_VISIBLE_FACT"));assert.ok(profile.claims.some(x=>x.text==="Orange 60pcs"&&x.safety==="LISTING_SUPPLIED_FACT"));assert.ok(!profile.claims.some(x=>x.text.includes("PayLater")));});
test("category knowledge supplies only a generic gummy function and no audience or medical claim",async()=>{const result=await resolveProductIntelligence(base,input),profile=result.product_profile!;assert.equal(result.primary_function,"suplemen dalam bentuk gummy");assert.equal(result.primary_function_source,"category_knowledge");assert.equal(result.primary_function_confidence,"medium");assert.equal(result.target_audience,"Belum disahkan");assert.equal(profile.micro_question_required,false);assert.doesNotMatch(JSON.stringify(profile.claims),/children|kanak|immunity|pregnan|medical|snack/i);});
test("unknown category requires one micro-question while obvious cleanser does not",async()=>{const unknown=await resolveProductIntelligence({...base,name:"Produk X",brand:"",category:"misc",physical_product_text:[],listing_text:[],ui_text:[]},input);assert.equal(unknown.product_profile?.micro_question_required,true);const cleanser=await resolveProductIntelligence({...base,name:"Gentle Facial Cleanser",category:"facial cleanser",physical_product_text:["Gentle Facial Cleanser"]},input);assert.equal(cleanser.product_profile?.micro_question_required,false);assert.match(cleanser.primary_function||"",/membersihkan wajah/);});
test("matching product page enriches profile and wrong product is discarded",async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>new Response('<title>Mommy Hana Vitamin C Gummies Official</title><meta property="og:description" content="Mommy Hana Orange 60pcs">',{status:200,headers:{"content-type":"text/html"}});const matched=await resolveProductIntelligence(base,{...input,product_url:"https://shop.example/product"});assert.equal(matched.product_profile?.product_page_fetch_status,"success");assert.equal(matched.product_profile?.product_page_identity_match,true);assert.ok(matched.product_profile?.productPageFacts.length);globalThis.fetch=async()=>new Response("<title>Completely Different Phone Case</title>",{status:200,headers:{"content-type":"text/html"}});const wrong=await resolveProductIntelligence(base,{...input,product_url:"https://shop.example/wrong"});assert.equal(wrong.product_profile?.product_page_fetch_status,"identity_mismatch");assert.deepEqual(wrong.product_profile?.productPageFacts,[]);}finally{globalThis.fetch=original;}});
test("TikTok, Shopee, and broken redirect failures fall back without blocking",async()=>{const original=globalThis.fetch;try{for(const url of ["https://www.tiktok.com/shop/item","https://shopee.com.my/item","https://shop.example/redirect"]){globalThis.fetch=async()=>url.includes("redirect")?new Response(null,{status:302}):new Response("blocked",{status:403,headers:{"content-type":"text/html"}});const result=await resolveProductIntelligence(base,{...input,product_url:url});assert.equal(result.product_profile?.product_page_fetch_status,"failed");assert.ok((result.product_profile?.productIdentity.length||0)>0);}}finally{globalThis.fetch=original;}});
test("user title is cached in the resolved profile and changing it changes resolution input",async()=>{const a=await resolveProductIntelligence({...base,physical_product_text:[],listing_text:[]},{...input,product_title:"Mommy Hana Gummies Orange"}),b=await resolveProductIntelligence({...base,physical_product_text:[],listing_text:[]},{...input,product_title:"Mommy Hana Gummies Lemon"});assert.deepEqual(a.product_profile?.userFacts,["Mommy Hana Gummies Orange"]);assert.notDeepEqual(a.product_profile?.userFacts,b.product_profile?.userFacts);});
test("one short purpose answer resolves a required micro-question",async()=>{const product=await resolveProductIntelligence({...base,name:"Produk X",category:"misc",physical_product_text:[],listing_text:[]},input),project={id:"p",owner:"o",created_at:1,updated_at:1,stage:"ready",image_count:1,input_key:"x",product} as ProductProject;assert.equal(project.product?.product_profile?.micro_question_required,true);applyCorrections(project,{corrections:"",primary_function:"Digunakan untuk menyimpan barang"});assert.equal(project.product?.primary_function_source,"user_supplied");assert.equal(project.product?.product_profile?.micro_question_required,false);});
test("packaging semantic identity beats isolated KIDS and generic container copy",async()=>{const result=await resolveProductIntelligence({...base,name:"KIDS",physical_product_text:["Mommy Hana","Vitamin C Gummies","KIDS","Chewable Gummies","Orange Flavour","60 gummies"],observed_features:["Bekas silinder lutsinar berwarna gelap","Penutup jingga"]},input);assert.equal(result.name,"Mommy Hana Vitamin C Gummies Chewable Gummies Orange Flavour 60 gummies");assert.notEqual(result.name,"KIDS");assert.ok(result.product_profile?.salesIntelligenceFacts.includes("Orange Flavour"));assert.ok(result.product_profile?.visualIdentityFacts.includes("Bekas silinder lutsinar berwarna gelap"));assert.ok(!result.product_profile?.salesIntelligenceFacts.some(x=>/bekas silinder/i.test(x)));assert.equal(result.primary_function,"suplemen dalam bentuk gummy");});
