import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { providerReferences } from "../cloud/reference-preprocessing";
import type { JobInput, ProductAnalysis, ReferenceAssessment } from "../src/lib/pawarna/types";

const input:JobInput={images:["data:image/png;base64,ORIGINAL"],mode:"Auto",instructions:"",angle_seed:"x"};
const base:ProductAnalysis={name:"Set",brand:"",category:"Cookware",confidence:"high",visible_text:"Dessini",description:"Red cookware set",observed_features:["set"],search_query:"",uncertainty:"",reference_indices:[0]};
const assessment=(value:Partial<ReferenceAssessment>):ReferenceAssessment=>({index:0,reference_type:"SCREENSHOT_OR_UI_IMAGE",detected_ui:true,product_region:{left:.1,top:.15,right:.9,bottom:.88},ui_overlap_product:false,sanitization_confidence:"high",reason:"Complete set centred away from UI",...value});
const clean=async()=>({postSanitizationClean:true,residualUiDetected:false,sanitizationConfidence:"high" as const,rectangularCropInsufficient:false});
const dirty=async()=>({postSanitizationClean:false,residualUiDetected:true,sanitizationConfidence:"low" as const,rectangularCropInsufficient:true});

test("clean product photo uses original without preprocessing and allows provider",async()=>{let crops=0,validations=0;const result=await providerReferences(input,{...base,reference_preprocessing:[assessment({reference_type:"CLEAN_PRODUCT_IMAGE",detected_ui:false,product_region:null})]},[0],async()=>{crops++;return"bad"},async()=>{validations++;return clean()});assert.equal(crops,0);assert.equal(validations,0);assert.deepEqual(result.media,[input.images[0]]);assert.equal(result.providerCallAllowed,true);assert.equal(result.audit[0].referencePathUsed,"original_clean");});
test("dirty screenshot sends only a post-validated sanitized reference",async()=>{const result=await providerReferences(input,{...base,reference_preprocessing:[assessment({})]},[0],async()=>"data:image/png;base64,SANITIZED",clean);assert.deepEqual(result.media,["data:image/png;base64,SANITIZED"]);assert.ok(!result.media.includes(input.images[0]));assert.equal(result.providerCallAllowed,true);assert.equal(result.audit[0].referencePathUsed,"sanitized_clean");assert.equal(result.audit[0].sanitization_applied,true);});
test("dirty screenshot with residual UI blocks provider",async()=>{const result=await providerReferences(input,{...base,reference_preprocessing:[assessment({})]},[0],async()=>"data:image/png;base64,DIRTY_CROP",dirty);assert.deepEqual(result.media,[]);assert.equal(result.providerCallAllowed,false);assert.equal(result.audit[0].residualUiDetected,true);assert.equal(result.audit[0].referencePathUsed,"blocked_unsafe");});
test("uncertain, overlapping, or low-confidence references block provider",async()=>{for(const a of [assessment({reference_type:"UNCERTAIN",product_region:null,sanitization_confidence:"low"}),assessment({ui_overlap_product:true}),assessment({sanitization_confidence:"low"})]){let calls=0;const result=await providerReferences(input,{...base,reference_preprocessing:[a]},[0],async()=>{calls++;return"bad"},clean);assert.equal(calls,0);assert.equal(result.providerCallAllowed,false);assert.deepEqual(result.media,[]);}});
test("genuine physical product branding does not trigger UI validation on a clean photo",async()=>{let validations=0;const result=await providerReferences(input,{...base,visible_text:"Dessini logo printed on cookware",reference_preprocessing:[assessment({reference_type:"CLEAN_PRODUCT_IMAGE",detected_ui:false,product_region:null})]},[0],async()=>"bad",async()=>{validations++;return dirty()});assert.equal(validations,0);assert.equal(result.providerCallAllowed,true);});
test("Dessini crop retaining PayLater and installment UI fails regression gate",async()=>{const result=await providerReferences(input,{...base,name:"Dessini red cookware set",reference_preprocessing:[assessment({product_region:{left:.05,top:.28,right:.95,bottom:.65}})]},[0],async()=>"data:image/jpeg;base64,DESSINI_WITH_PAYLATER_AND_INSTALLMENTS",dirty);assert.equal(result.audit[0].postSanitizationClean,false);assert.equal(result.audit[0].providerCallAllowed,false);assert.deepEqual(result.media,[]);});
test("production routing contains no Dessini project special case",()=>{const factory=readFileSync(new URL("../cloud/factory.ts",import.meta.url),"utf8"),config=readFileSync(new URL("../wrangler.jsonc",import.meta.url),"utf8");assert.doesNotMatch(factory+config,/70feb4d4-979b-41f5-add3-f369ac114551|PAWARNA_OMNI_REFERENCE_ONLY_PRODUCT_ID/);});
