import type { StoryRecord } from "@/lib/types";

const accessedAt = "2026-09-03";
const source = (id: string, title: string, publisher: string, type: StoryRecord["sources"][number]["type"], url: string, date?: string) => ({ id, title, publisher, type, url, date, accessedAt, reliabilityLevel: type });
const claim = (id: string, claimText: string, narration: string, type: StoryRecord["claims"][number]["type"], sourceIds: string[], priority: StoryRecord["claims"][number]["priority"], visualIntent: StoryRecord["claims"][number]["visualIntent"], confidence: "HIGH" | "MEDIUM" | "LOW" = "HIGH") => ({ id, claim: claimText, narration, type, confidence, sourceIds, priority, visualIntent });

export const mysteryCatalog: StoryRecord[] = [
  {
    id: "dyatlov-pass", title: "Insiden Dyatlov Pass", country: "Rusia", region: "Pergunungan Ural", year: 1959, decade: "1950-an", category: "HISTORICAL_MYSTERY", caseStatus: "PARTIALLY_EXPLAINED",
    summary: "Sembilan pendaki maut selepas meninggalkan khemah mereka dalam cuaca ekstrem.", entityIds: ["Q207006"], sourceHints: ["Nature Communications", "Britannica"], visualSearchTerms: ["Dyatlov Pass group", "Dyatlov Pass tent", "Ural Mountains winter"], researchScore: .96, visualScore: .91, sourceCoveragePotential: "good",
    sources: [source("d1", "Mechanisms of slab avalanche release and impact in the Dyatlov Pass incident", "Communications Earth & Environment", "ACADEMIC", "https://www.nature.com/articles/s43247-020-00081-8", "2021"), source("d2", "Dyatlov Pass incident", "Encyclopaedia Britannica", "REFERENCE", "https://www.britannica.com/event/Dyatlov-Pass-incident")],
    claims: [claim("d-c1", "The tent was cut open from the inside.", "Khemah mereka ditemui terkoyak dari bahagian dalam.", "VERIFIED", ["d1", "d2"], "HOOK_WORTHY", "EVIDENCE"), claim("d-c2", "Nine experienced hikers died in the northern Urals in February 1959.", "Sembilan pendaki berpengalaman maut di Ural pada Februari 1959.", "VERIFIED", ["d1", "d2"], "ESSENTIAL_CONTEXT", "MAP"), claim("d-c3", "Some victims left without adequate clothing or footwear.", "Ada yang keluar tanpa pakaian dan kasut yang cukup.", "VERIFIED", ["d1", "d2"], "ESCALATION_DETAIL", "ARCHIVAL_PHOTO"), claim("d-c4", "Several bodies had severe traumatic injuries.", "Beberapa mayat pula mengalami kecederaan dalaman yang serius.", "VERIFIED", ["d1", "d2"], "TWIST", "FACT_CARD"), claim("d-c5", "A 2021 study showed a delayed slab avalanche was physically plausible.", "Kajian pada 2021 menunjukkan runtuhan salji kepingan memang boleh berlaku.", "EXPLAINED_LATER", ["d1"], "THEORY", "THEORY_CARD"), claim("d-c6", "The avalanche model does not reconstruct every individual action that night.", "Tapi model itu tidak menjelaskan setiap tindakan mereka malam itu.", "UNRESOLVED", ["d1"], "COUNTERPOINT", "ENDING")]
  },
  {
    id: "mary-celeste", title: "Misteri Mary Celeste", country: "Atlantik", region: "Kepulauan Azores", year: 1872, decade: "1870-an", category: "HISTORICAL_MYSTERY", caseStatus: "UNSOLVED",
    summary: "Sebuah kapal ditemui masih boleh belayar, tetapi semua orang di atasnya hilang.", entityIds: ["Q170509"], sourceHints: ["Smithsonian", "Britannica"], visualSearchTerms: ["Mary Celeste ship", "Mary Celeste engraving", "Azores map"], researchScore: .95, visualScore: .9, sourceCoveragePotential: "good",
    sources: [source("m1", "The Mystery of the Mary Celeste", "Smithsonian Magazine", "INSTITUTIONAL", "https://www.smithsonianmag.com/history/abandoned-ship-the-mary-celeste-174488104/"), source("m2", "Mary Celeste", "Encyclopaedia Britannica", "REFERENCE", "https://www.britannica.com/topic/Mary-Celeste")],
    claims: [claim("m-c1", "Mary Celeste was found abandoned but seaworthy.", "Kapal itu masih boleh belayar. Tapi seluruh kru sudah hilang.", "VERIFIED", ["m1", "m2"], "HOOK_WORTHY", "ARCHIVAL_PHOTO"), claim("m-c2", "The ship was discovered near the Azores in December 1872.", "Ia ditemui dekat Azores pada Disember 1872.", "VERIFIED", ["m1", "m2"], "ESSENTIAL_CONTEXT", "MAP"), claim("m-c3", "The captain, his family and crew were missing.", "Kapten, keluarganya dan semua kru tidak ditemui.", "VERIFIED", ["m1", "m2"], "ESCALATION_DETAIL", "PORTRAIT"), claim("m-c4", "The lifeboat was gone while much of the cargo remained.", "Bot penyelamat hilang, tetapi banyak muatan masih berada di kapal.", "VERIFIED", ["m1", "m2"], "TWIST", "EVIDENCE"), claim("m-c5", "Historians have proposed a temporary evacuation caused by fear of an explosion.", "Satu teori mencadangkan mereka turun kerana menyangka letupan akan berlaku.", "THEORY", ["m1"], "THEORY", "THEORY_CARD"), claim("m-c6", "No explanation has established what happened to the ten people aboard.", "Tiada penjelasan dapat memastikan nasib sepuluh orang di atasnya.", "UNRESOLVED", ["m1", "m2"], "PAYOFF", "ENDING")]
  },
  {
    id: "db-cooper", title: "Kehilangan D. B. Cooper", country: "Amerika Syarikat", region: "Pacific Northwest", year: 1971, decade: "1970-an", category: "CRIME_MYSTERY", caseStatus: "UNSOLVED",
    summary: "Perampas pesawat terjun dengan wang tebusan lalu lenyap tanpa identiti pasti.", entityIds: ["Q332028"], sourceHints: ["FBI"], visualSearchTerms: ["DB Cooper FBI", "Boeing 727 Northwest Orient", "DB Cooper sketch"], researchScore: .98, visualScore: .88, sourceCoveragePotential: "good",
    sources: [source("c1", "D.B. Cooper Hijacking", "Federal Bureau of Investigation", "PRIMARY", "https://www.fbi.gov/history/famous-cases/db-cooper-hijacking")],
    claims: [claim("c-c1", "The hijacker parachuted from a Boeing 727 with ransom money.", "Dia terjun dari pesawat bersama wang tebusan, kemudian lenyap.", "VERIFIED", ["c1"], "HOOK_WORTHY", "ARCHIVAL_PHOTO"), claim("c-c2", "The hijacking occurred on November 24, 1971.", "Rampasan itu berlaku pada 24 November 1971.", "VERIFIED", ["c1"], "ESSENTIAL_CONTEXT", "TIMELINE"), claim("c-c3", "He used the name Dan Cooper to buy his ticket.", "Nama pada tiketnya ialah Dan Cooper, bukan D. B. Cooper.", "VERIFIED", ["c1"], "TWIST", "DOCUMENT"), claim("c-c4", "He received 200,000 dollars and four parachutes.", "Dia menerima dua ratus ribu dolar dan empat payung terjun.", "VERIFIED", ["c1"], "ESCALATION_DETAIL", "FACT_CARD"), claim("c-c5", "A portion of the ransom was found in 1980.", "Pada 1980, sebahagian wang itu ditemui tertanam dekat sungai.", "VERIFIED", ["c1"], "TWIST", "EVIDENCE"), claim("c-c6", "The FBI ended active investigation in 2016 without identifying him.", "FBI menamatkan siasatan aktif tanpa mengenal pasti siapa dia.", "UNRESOLVED", ["c1"], "PAYOFF", "ENDING")]
  },
  {
    id: "roswell", title: "Apa Sebenarnya Jatuh di Roswell?", country: "Amerika Syarikat", region: "New Mexico", year: 1947, decade: "1940-an", category: "CONSPIRACY_THEORY", caseStatus: "PARTIALLY_EXPLAINED",
    summary: "Dakwaan UFO terkenal yang kemudian dikaitkan dengan projek belon rahsia Amerika.", entityIds: ["Q213511"], sourceHints: ["US Air Force", "National Archives"], visualSearchTerms: ["Roswell incident", "Project Mogul balloon", "Roswell debris"], researchScore: .97, visualScore: .92, sourceCoveragePotential: "good",
    sources: [source("r1", "The Roswell Report: Fact versus Fiction in the New Mexico Desert", "U.S. Air Force", "PRIMARY", "https://www.afhra.af.mil/Portals/16/documents/AFD-101201-038.pdf"), source("r2", "Project BLUE BOOK", "U.S. National Archives", "INSTITUTIONAL", "https://www.archives.gov/research/military/air-force/ufos")],
    claims: [claim("r-c1", "A 1947 press release said a flying disc had been recovered.", "Pada 1947, tentera mengumumkan mereka menemui sebuah ‘cakera terbang’.", "REPORTED", ["r1"], "HOOK_WORTHY", "NEWSPAPER"), claim("r-c2", "The announcement was quickly changed to a weather balloon explanation.", "Tidak lama kemudian, kenyataan itu berubah kepada belon cuaca.", "VERIFIED", ["r1"], "ESCALATION_DETAIL", "TIMELINE"), claim("r-c3", "Alien spacecraft and bodies became popular later claims.", "Bertahun-tahun kemudian, muncul dakwaan kapal dan mayat makhluk asing.", "REPORTED", ["r1"], "THEORY", "THEORY_CARD", "LOW"), claim("r-c4", "The Air Force linked the debris to the classified Project Mogul balloon program.", "Laporan Tentera Udara mengaitkan serpihan itu dengan Projek Mogul yang dirahsiakan.", "EXPLAINED_LATER", ["r1"], "TWIST", "DOCUMENT"), claim("r-c5", "The official reports found no evidence of extraterrestrial occupants.", "Laporan rasmi tidak menemui bukti penghuni dari luar bumi.", "DISPUTED", ["r1"], "COUNTERPOINT", "FACT_CARD"), claim("r-c6", "The secrecy around the balloon project helped the legend persist.", "Rahsia projek itu membantu legenda Roswell terus hidup.", "EXPLAINED_LATER", ["r1", "r2"], "PAYOFF", "ENDING")]
  },
  {
    id: "amelia-earhart", title: "Kehilangan Amelia Earhart", country: "Pasifik", region: "Pulau Howland", year: 1937, decade: "1930-an", category: "DISAPPEARANCE", caseStatus: "UNSOLVED",
    summary: "Juruterbang terkenal hilang ketika cuba mengelilingi dunia.", entityIds: ["Q6691"], sourceHints: ["Smithsonian", "National Archives"], visualSearchTerms: ["Amelia Earhart Lockheed Electra", "Howland Island", "Amelia Earhart portrait"], researchScore: .96, visualScore: .96, sourceCoveragePotential: "good",
    sources: [source("a1", "Amelia Earhart", "Smithsonian National Air and Space Museum", "INSTITUTIONAL", "https://airandspace.si.edu/explore/stories/amelia-earhart"), source("a2", "Records Relating to Amelia Earhart", "U.S. National Archives", "PRIMARY", "https://www.archives.gov/research/transportation/aviation/amelia-earhart")],
    claims: [claim("a-c1", "Earhart's aircraft disappeared near Howland Island.", "Pesawatnya hilang ketika sebuah kapal sedang menunggu isyarat radio.", "VERIFIED", ["a1", "a2"], "HOOK_WORTHY", "MAP"), claim("a-c2", "Earhart and Fred Noonan vanished on July 2, 1937.", "Amelia Earhart dan Fred Noonan hilang pada 2 Julai 1937.", "VERIFIED", ["a1", "a2"], "ESSENTIAL_CONTEXT", "TIMELINE"), claim("a-c3", "They were trying to reach tiny Howland Island during a world flight.", "Mereka cuba mencari Pulau Howland dalam penerbangan mengelilingi dunia.", "VERIFIED", ["a1"], "ESCALATION_DETAIL", "MAP"), claim("a-c4", "Radio messages indicated they were low on fuel and could not see the island.", "Mesej radio menunjukkan minyak semakin habis dan pulau itu belum kelihatan.", "REPORTED", ["a1", "a2"], "TWIST", "DOCUMENT"), claim("a-c5", "The most accepted explanation is that the aircraft ran out of fuel and crashed at sea.", "Penjelasan utama ialah pesawat kehabisan minyak lalu jatuh ke laut.", "THEORY", ["a1"], "THEORY", "THEORY_CARD"), claim("a-c6", "No confirmed wreckage has resolved the disappearance.", "Tiada bangkai pesawat yang disahkan menamatkan misteri itu.", "UNRESOLVED", ["a1", "a2"], "PAYOFF", "ENDING")]
  },
  {
    id: "voynich", title: "Manuskrip Voynich", country: "Itali / Eropah", region: "Tidak diketahui", year: 1404, decade: "Abad ke-15", category: "HISTORICAL_MYSTERY", caseStatus: "UNSOLVED",
    summary: "Buku bergambar dalam tulisan yang masih belum dapat dibaca dengan pasti.", entityIds: ["Q193390"], sourceHints: ["Yale Beinecke Library"], visualSearchTerms: ["Voynich manuscript", "Voynich manuscript folio", "Beinecke MS 408"], researchScore: .98, visualScore: .99, sourceCoveragePotential: "good",
    sources: [source("v1", "Voynich Manuscript (Beinecke MS 408)", "Yale University Library", "INSTITUTIONAL", "https://collections.library.yale.edu/catalog/2002046")],
    claims: [claim("v-c1", "The manuscript is written in an unknown script.", "Buku ini penuh tulisan, tapi tiada siapa dapat membacanya dengan pasti.", "VERIFIED", ["v1"], "HOOK_WORTHY", "DOCUMENT"), claim("v-c2", "Radiocarbon dating places its parchment in the early fifteenth century.", "Ujian karbon meletakkan perkamen itu pada awal abad kelima belas.", "VERIFIED", ["v1"], "ESSENTIAL_CONTEXT", "TIMELINE"), claim("v-c3", "Its pages include unfamiliar plants, astronomical diagrams and bathing figures.", "Halamannya menunjukkan tumbuhan pelik, rajah bintang dan figura sedang mandi.", "VERIFIED", ["v1"], "ESCALATION_DETAIL", "ARCHIVAL_PHOTO"), claim("v-c4", "Many proposed solutions have not achieved scholarly consensus.", "Banyak orang mendakwa sudah memecahkan kodnya.", "REPORTED", ["v1"], "THEORY", "THEORY_CARD"), claim("v-c5", "No proposed decoding has gained broad acceptance.", "Masalahnya, tiada tafsiran mendapat penerimaan luas.", "DISPUTED", ["v1"], "COUNTERPOINT", "FACT_CARD"), claim("v-c6", "Its author, language and purpose remain unknown.", "Penulis, bahasa dan tujuan sebenar buku ini masih tidak diketahui.", "UNRESOLVED", ["v1"], "PAYOFF", "ENDING")]
  },
  {
    id: "mh370", title: "Kehilangan MH370", country: "Malaysia", region: "Lautan Hindi", year: 2014, decade: "Moden", category: "DISAPPEARANCE", caseStatus: "UNSOLVED",
    summary: "Pesawat Malaysia Airlines hilang dan lokasi utamanya masih belum ditemukan.", entityIds: ["Q15901655"], sourceHints: ["MOT Malaysia", "ATSB"], visualSearchTerms: ["Malaysia Airlines Boeing 777", "MH370 search map", "MH370 debris"], researchScore: .99, visualScore: .94, sourceCoveragePotential: "good",
    sources: [source("h1", "MH370 Safety Investigation Report", "Ministry of Transport Malaysia", "PRIMARY", "https://www.mot.gov.my/en/aviation/reports/mh370-safety-investigation-report"), source("h2", "The Operational Search for MH370", "Australian Transport Safety Bureau", "PRIMARY", "https://www.atsb.gov.au/publications/investigation_reports/2014/aair/ae-2014-054")],
    claims: [claim("h-c1", "MH370 disappeared from civilian radar during a routine flight.", "Sebuah pesawat dengan 239 orang hilang selepas lenyap daripada radar awam.", "VERIFIED", ["h1", "h2"], "HOOK_WORTHY", "MAP"), claim("h-c2", "The Boeing 777 left Kuala Lumpur for Beijing on March 8, 2014.", "MH370 berlepas dari Kuala Lumpur ke Beijing pada 8 Mac 2014.", "VERIFIED", ["h1"], "ESSENTIAL_CONTEXT", "TIMELINE"), claim("h-c3", "Military radar indicated the aircraft turned back across Peninsular Malaysia.", "Radar tentera menunjukkan pesawat itu berpatah balik merentasi Semenanjung.", "VERIFIED", ["h1"], "TWIST", "MAP"), claim("h-c4", "Satellite data redirected the search toward the southern Indian Ocean.", "Data satelit kemudian mengalihkan pencarian ke selatan Lautan Hindi.", "VERIFIED", ["h1", "h2"], "ESCALATION_DETAIL", "EVIDENCE"), claim("h-c5", "Debris confirmed to be from MH370 was recovered far from the main search area.", "Serpihan yang disahkan milik MH370 ditemui jauh dari kawasan carian utama.", "VERIFIED", ["h1", "h2"], "TWIST", "ARCHIVAL_PHOTO"), claim("h-c6", "The main wreckage and exact cause have not been established.", "Bangkai utama dan punca tepat kehilangan masih belum dikenal pasti.", "UNRESOLVED", ["h1", "h2"], "PAYOFF", "ENDING")]
  },
  {
    id: "singapore-stone", title: "Tulisan Batu Singapura", country: "Malaya", region: "Singapura", year: 1819, decade: "1800-an", category: "ARCHAEOLOGICAL_MYSTERY", caseStatus: "PARTIALLY_EXPLAINED",
    summary: "Serpihan batu bertulis yang bahasanya masih diperdebatkan selepas batu asal dimusnahkan.", entityIds: ["Q7530000"], sourceHints: ["National Library Board Singapore", "National Museum of Singapore"], visualSearchTerms: ["Singapore Stone", "Singapore Stone inscription", "Singapore River mouth historic"], researchScore: .91, visualScore: .83, sourceCoveragePotential: "good",
    sources: [source("s1", "Singapore Stone", "National Library Board Singapore", "INSTITUTIONAL", "https://www.nlb.gov.sg/main/article-detail?cmsuuid=540a21c7-7c8a-4ad1-b96a-9bc65e86c4c4"), source("s2", "Singapore Stone", "National Heritage Board Singapore", "INSTITUTIONAL", "https://www.roots.gov.sg/Collection-Landing/listing/1028258")],
    claims: [claim("s-c1", "Most of the inscribed boulder was destroyed by blasting.", "Sebuah batu bertulis dimusnahkan sebelum tulisannya sempat difahami.", "VERIFIED", ["s1", "s2"], "HOOK_WORTHY", "DOCUMENT"), claim("s-c2", "The boulder stood near the mouth of the Singapore River.", "Batu itu berdiri dekat muara Sungai Singapura.", "VERIFIED", ["s1"], "ESSENTIAL_CONTEXT", "MAP"), claim("s-c3", "It was blown up in 1843 to widen a passage.", "Pada 1843, ia diletupkan untuk meluaskan laluan.", "VERIFIED", ["s1", "s2"], "TWIST", "TIMELINE"), claim("s-c4", "Only a few fragments were preserved.", "Cuma beberapa serpihan sempat diselamatkan.", "VERIFIED", ["s1", "s2"], "ESCALATION_DETAIL", "EVIDENCE"), claim("s-c5", "Scholars have proposed several scripts and languages.", "Pengkaji mencadangkan beberapa bahasa dan sistem tulisan.", "THEORY", ["s1"], "THEORY", "THEORY_CARD"), claim("s-c6", "The surviving text has not been conclusively deciphered.", "Tetapi tulisan yang tinggal belum dapat ditafsir secara muktamad.", "UNRESOLVED", ["s1", "s2"], "PAYOFF", "ENDING")]
  }
];

export const categoryLabels: Record<StoryRecord["category"], string> = {
  UNSOLVED_MYSTERY: "Misteri belum selesai", HISTORICAL_MYSTERY: "Misteri sejarah", DISAPPEARANCE: "Kehilangan", STRANGE_EVENT: "Peristiwa pelik", CRIME_MYSTERY: "Misteri jenayah", CONSPIRACY_THEORY: "Teori konspirasi", PARANORMAL_CLAIM: "Dakwaan paranormal", URBAN_LEGEND: "Legenda bandar", ARCHAEOLOGICAL_MYSTERY: "Misteri arkeologi", UNEXPLAINED_PHENOMENON: "Fenomena belum dijelaskan"
};

export const caseStatusLabels: Record<StoryRecord["caseStatus"], string> = {
  UNSOLVED: "Belum selesai", PARTIALLY_EXPLAINED: "Sebahagiannya dijelaskan", SOLVED: "Selesai", DISPUTED: "Dipertikaikan", LEGEND: "Legenda", REPORTED_CLAIM: "Dakwaan dilaporkan"
};

export function getMysteryStory(id: string) { return mysteryCatalog.find((story) => story.id === id); }
