// Single source of truth for global generation rules. Both current and legacy adapters use these.
export const SPOKEN_CTA = "Klik link kat bawah.";
export const PAWARNA_VIDEO_EXECUTION_LOCK = `Create ONE finished approximately 10-second vertical 9:16 video. Begin immediately with actual moving scene footage. Uploaded reference images are visual ingredients only: never a first-frame still, still intro, slideshow, screenshot, app interface or fake video frame. Zero generated on-screen text: no subtitles, captions, prices, CTA graphics, random letters, text overlays or fake UI. Physical printed product labels remain unchanged.`;
export const PRODUCT_LOCK = `The uploaded PRODUCT photographs are the absolute visual source of truth. Preserve exact product shape, size, proportions, packaging, cap, bottle, label layout, logo/brand identity and visible colours. Never elongate bottles, widen packaging, invent logos, change colours, redesign labels, generate alternate packaging or oversize the product. Keep realistic physical scale relative to hands and surroundings. Do not reveal unseen surfaces or invent hidden product parts. Do not transform, replace or beautify the packaging. Books remain closed unless interior reference photographs were uploaded; never invent unseen pages, back cover, interiors or contents.`;
export const CAMERA_LOCK = `Use a believable flagship-smartphone camera with natural handheld micro-movement and small lateral/body movement when appropriate. Physically believable movement and gestures. No tripod feel, cinematic glide, aggressive zoom, artificial hero-spin or exaggerated influencer acting. POV styles may use genuine POV behaviour. No TV-commercial cinematic footage.`;
export const PAWARNA_VISUAL_MASTER_LOCK = `Realistic flagship-smartphone UGC footage: a good creator filming with a flagship smartphone in good light. Bright, clean, crisp and sharp; natural local contrast, clean whites, accurate product colour, realistic material texture and skin, natural dynamic range. Believable Malaysian everyday environment, no fixed ethnicity. Realistic motion blur only when physically appropriate. No grey wash, dull/kusam output, yellow/orange cinematic grading, moody darkness, dreamy softness, excessive bokeh, AI plastic skin, waxy skin, plastic-looking product, fake HDR or overprocessed commercial/studio look.`;
export const LANGUAGE_AUDIO_LOCK = `Speak only Bahasa Melayu Malaysia: Malaysian Malay only, conversational local language; do not drift into Indonesian or unnecessarily formal Malay. Full readable words, no invented claims or extra improvised sentences. Audible human Malay speech, natural delivery, clear foreground voice, no robotic TTS feeling or loud music competing with speech. Complete the supplied script exactly once. Realistic lip sync when a creator is visible. CTA is exactly "${SPOKEN_CTA}" Never change it to "Klik pautan." Do not rush or truncate the CTA; end naturally only after the spoken CTA is complete.`;
export const SILENT_AUDIO_LOCK = `VOICEOVER: OFF. No dialogue, speech, singing, lip movement suggesting speech or spoken CTA. No captions or generated text. Only quiet natural ambient sound. End naturally after the visual payoff.`;
export function globalPromptLocks(voice = true) {
  return ["PAWARNA_VIDEO_EXECUTION_LOCK: " + PAWARNA_VIDEO_EXECUTION_LOCK,
    "PAWARNA_VISUAL_MASTER_LOCK: " + PAWARNA_VISUAL_MASTER_LOCK,
    "PRODUCT_LOCK: " + PRODUCT_LOCK, "CAMERA_LOCK: " + CAMERA_LOCK,
    "LANGUAGE_AUDIO_LOCK: " + (voice ? LANGUAGE_AUDIO_LOCK : SILENT_AUDIO_LOCK)];
}
