import type { IntelligenceSource, JobInput, ProductAnalysis, ProductProfile } from "./types";

const mappings:[RegExp,string][]=[[/thinning hair|hair loss|hair fall|rambut (?:makin )?(?:menipis|nipis|gugur)/i,"penjagaan rambut yang menipis dan mudah gugur"],[/hair care|penjagaan rambut|hair (?:water )?spray|syampu|shampoo/i,"digunakan untuk penjagaan rambut"],[/facial cleanser|pencuci muka/i,"digunakan untuk membersihkan wajah"],[/dishwashing liquid|cecair pencuci pinggan/i,"digunakan untuk mencuci pinggan"],[/portable fan|kipas mudah alih/i,"digunakan untuk menghasilkan aliran udara mudah alih"],[/water bottle|botol air/i,"digunakan untuk membawa minuman"],[/vitamin.*gumm|gumm.*vitamin|gumm.*supplement/i,"suplemen dalam bentuk gummy"],[/phone stand|pemegang telefon/i,"digunakan untuk menyokong telefon"],[/non.?stick cookware|cookware|peralatan memasak|kuali|periuk/i,"peralatan untuk memasak"]];
const source=(value:unknown):IntelligenceSource=>["physical_packaging","listing_text","product_page","user_supplied","category_knowledge","creator_experience","social_proof","price_promo","scarcity","inferred"].includes(String(value))?value as IntelligenceSource:"unknown";
const clean=(items:unknown)=>Array.isArray(items)?[...new Set(items.filter(x=>typeof x==="string"&&x.trim()).map(x=>x.trim()))].slice(0,30):[];
const tokens=(value:string)=>new Set(value.toLowerCase().match(/[a-z0-9]{3,}/g)?.filter(x=>!["product","official","shop","store","with","untuk","yang","dan"].includes(x))||[]);
const identityMatch=(a:string,b:string)=>{const aa=tokens(a),bb=tokens(b);return [...aa].some(x=>bb.has(x));};
const weakIdentity=/^(kids?|new|original|premium|plus|baru|asli)$/i;
const genericVisual=/\b(?:bekas|botol|kotak|container|cylindrical|silinder|rectangular|segi empat|plastic|plastik|glass|kaca|cap|penutup|label|berwarna|colour|color|gelap|cerah|kecil|besar)\b/i;
const semantic=(value:string)=>!weakIdentity.test(value.trim())&&!genericVisual.test(value);
const identityFromPackaging=(product:ProductAnalysis,physical:string[])=>{
  const parts=[product.brand,...physical.filter(semantic),product.variant||""]
    .flatMap(value=>value.split(/[|•\n]/)).map(value=>value.trim()).filter(Boolean);
  const unique=[...new Set(parts.filter(value=>!weakIdentity.test(value)))];
  const joined=unique.join(" ").replace(/\b(\w+(?:\s+\w+){0,3})(?:\s+\1)\b/gi,"$1").trim();
  return joined.split(/\s+/).slice(0,12).join(" ");
};
const safeUrl=(value:string)=>{const u=new URL(value);if(u.protocol!=="https:"||u.username||u.password||u.port||/^(localhost|127\.|0\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[?::1\]?)$/i.test(u.hostname))throw new Error("unsafe_url");return u;};
const text=(html:string)=>{const title=/<title[^>]*>([^<]{1,300})<\/title>/i.exec(html)?.[1]||"",meta=[...html.matchAll(/<meta[^>]+(?:property|name)=["'](?:og:title|og:description|description)["'][^>]+content=["']([^"']{1,1000})["']/gi)].map(x=>x[1]),jsonLd=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap(match=>{try{const root=JSON.parse(match[1]),nodes=Array.isArray(root)?root:root?.["@graph"]||[root];return nodes.filter((node:Record<string,unknown>)=>String(node?.["@type"]||"").toLowerCase()==="product").flatMap((node:Record<string,unknown>)=>[node.name,node.description,node.sku,typeof node.brand==="object"&&(node.brand as {name?:unknown}).name].filter(x=>typeof x==="string") as string[]);}catch{return[];}});return [...new Set([title,...meta,...jsonLd].map(x=>x.replace(/&amp;/g,"&").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()).filter(Boolean))].slice(0,20);};
async function pageFacts(value:string){let url=safeUrl(value);for(let i=0;i<3;i++){const response=await fetch(url,{redirect:"manual",headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"PawarnaProductResolver/1.0"},signal:AbortSignal.timeout(10000)});if([301,302,303,307,308].includes(response.status)){const next=response.headers.get("location");if(!next)throw new Error("redirect_missing");url=safeUrl(new URL(next,url).href);continue;}if(!response.ok||!(response.headers.get("content-type")||"").includes("text/html"))throw new Error(`http_${response.status}`);if(Number(response.headers.get("content-length")||0)>1_000_000)throw new Error("page_too_large");return text((await response.text()).slice(0,1_000_000));}throw new Error("redirect_limit");}

export async function resolveProductIntelligence(product:ProductAnalysis,input:JobInput):Promise<ProductAnalysis>{
  const physical=clean(product.physical_product_text),listing=clean(product.listing_text),ui=clean(product.ui_text),user=input.product_title?[input.product_title]:[],combined=[product.category,product.name,...physical,...listing,...user].join(" ");
  let page:string[]=[],pageStatus:ProductProfile["product_page_fetch_status"]=input.product_url?"failed":"not_requested",pageMatch=false;
  if(input.product_url)try{const fetched=await pageFacts(input.product_url);pageMatch=fetched.length>0&&identityMatch([product.brand,product.name,...physical,...listing,...user].join(" "),fetched.join(" "));if(pageMatch){page=fetched;pageStatus="success";}else pageStatus="identity_mismatch";}catch(error){console.warn(JSON.stringify({event:"product_page_fetch_failed",reason:error instanceof Error?error.message:"unknown"}));}
  const category=mappings.find(([pattern])=>pattern.test(combined));
  let primary=(product.primary_function||"").trim(),primarySource=source(product.primary_function_source),primaryConfidence=product.primary_function_confidence||"low";
  if(!primary||/belum disahkan|unknown/i.test(primary)){if(category){primary=category[1];primarySource="category_knowledge";primaryConfidence="medium";}else{primary="";primarySource="unknown";primaryConfidence="low";}}
  let audience=(product.target_audience||"").trim(),audienceSource=source(product.target_audience_source),audienceConfidence=product.target_audience_confidence||"low";
  if(!audience||/belum disahkan|unknown/i.test(audience)){audience="";audienceSource="unknown";audienceConfidence="low";}
  const packagedIdentity=identityFromPackaging(product,physical);
  const analysedIdentity=!weakIdentity.test(product.name.trim())?product.name.trim():"";
  const identity=pageMatch&&page[0]?page[0]:packagedIdentity||analysedIdentity||listing.find(semantic)||input.product_title||product.name;
  const identitySource:IntelligenceSource=pageMatch?"product_page":packagedIdentity?"physical_packaging":listing.some(semantic)?"listing_text":input.product_title?"user_supplied":"unknown";
  const claims:ProductProfile["claims"]=[...physical.map(value=>({text:value,safety:"SAFE_VISIBLE_FACT" as const,source:"physical_packaging" as const})),...listing.map(value=>({text:value,safety:"LISTING_SUPPLIED_FACT" as const,source:"listing_text" as const})),...user.map(value=>({text:value,safety:"USER_SUPPLIED_FACT" as const,source:"user_supplied" as const})),...page.map(value=>({text:value,safety:"PRODUCT_PAGE_FACT" as const,source:"product_page" as const})),...(category?[{text:category[1],safety:"SAFE_CATEGORY_FUNCTION" as const,source:"category_knowledge" as const}]:[])];
  const salesIntelligenceFacts=[identity,...physical.filter(semantic),product.variant||"",primary,audience].filter(Boolean);
  const profile:ProductProfile={productIdentity:identity,product_identity_source:identitySource,category:product.category,primaryFunction:primary,primary_function_source:primarySource,primary_function_confidence:primaryConfidence,targetAudience:audience,target_audience_source:audienceSource,target_audience_confidence:audienceConfidence,variant:product.variant||"",visualIdentityFacts:product.observed_features,salesIntelligenceFacts:[...new Set(salesIntelligenceFacts)],observedFacts:product.observed_features,listingFacts:listing,userFacts:user,productPageFacts:page,safeCategoryFacts:category?[category[1]]:[],unknowns:[...(!primary?["primary_function"]:[]),...(!audience?["target_audience"]:[])],claims,confidence:product.confidence,listing_text_detected:listing.length>0,product_page_fetch_attempted:!!input.product_url,product_page_fetch_status:pageStatus,product_page_identity_match:pageMatch,category_knowledge_used:!!category,micro_question_required:!primary};
  console.log(JSON.stringify({event:"product_intelligence",product_identity_source:identitySource,primary_function_source:primarySource,target_audience_source:audienceSource,listing_text_detected:profile.listing_text_detected,product_page_fetch_attempted:profile.product_page_fetch_attempted,product_page_fetch_status:pageStatus,product_page_identity_match:pageMatch,category_knowledge_used:profile.category_knowledge_used,micro_question_required:profile.micro_question_required,final_intelligence_confidence:profile.confidence,ui_text_detected:ui.length>0}));
  return {...product,name:identity||product.name,physical_product_text:physical,listing_text:listing,ui_text:ui,primary_function:primary||"Belum disahkan",primary_function_source:primarySource,primary_function_confidence:primaryConfidence,target_audience:audience||"Belum disahkan",target_audience_source:audienceSource,target_audience_confidence:audienceConfidence,product_profile:profile};
}
