"use client";
/* eslint-disable @next/next/no-img-element -- Private images and local previews. */
import {useCallback,useEffect,useRef,useState,type ReactNode} from "react";
import {Home,FolderHeart,Plus,Wallet,UserRound,ArrowLeft,ArrowRight,Check,X,ImagePlus,Sparkles,Hand,Lightbulb,Coffee,Orbit,Pencil,Scan,Clapperboard,Download,RefreshCw,Mic,ShieldCheck,VolumeX,ChevronRight,LoaderCircle,Smartphone} from "lucide-react";
import {STAGES,type PublicJob} from "@/lib/pawarna/types";
import {DEFAULT_SETTINGS,VIDEO_STYLES,ANGLES,supportsCreator,recommendStyle,type GenerationSettings} from "@/lib/pawarna/settings";
import type {PublicProduct} from "@/lib/pawarna/projects";
import {usePwa} from "./usePwa";
import {JobDiagnostics} from "./JobDiagnostics";
import {ResearchSources} from "./ResearchSources";
import "./pawarna-native.css";

type Usage={id:string;name:string;attempts:number;recorded_cost:number;stage:string};
type Ready={gemini:boolean;nexabot:boolean;worker:boolean;paused:boolean};
const styleIcons=[Hand,Lightbulb,Coffee,Orbit,Sparkles,Pencil,Scan,Clapperboard];
const flow=["Produk","Style","Angle","Creator & Voice","Review"];
const styleName=(id?:string)=>VIDEO_STYLES.find(s=>s.id===id)?.label||"Gaya terdahulu";
const angleName=(id?:string)=>ANGLES.find(a=>a[0]===id)?.[1]||"Auto";
const subjectName=(s:string)=>({auto:"Auto",female_hands:"Tangan perempuan",male_hands:"Tangan lelaki",no_hands:"Tanpa tangan",female_creator:"Creator perempuan",male_creator:"Creator lelaki"}[s]||s);
const voiceName=(s:GenerationSettings)=>!s.voiceoverEnabled?"Visual sahaja":(s.voiceGender==="auto"?"Auto":s.voiceGender==="female"?"Perempuan Melayu":"Lelaki Melayu")+" · "+s.voiceStyle.replace("_"," ");
const done=(j:PublicJob)=>["completed","failed"].includes(j.stage);
function Choices({label,value,items,onChange}:{label:string;value:string;items:readonly (readonly [string,string])[];onChange:(v:string)=>void}){
 return <fieldset className={"pn-field "+(label==="Sales angle"?"pn-angle-options":"")}><legend>{label}</legend><div className="pn-chips">{items.map(([id,text])=><button type="button" key={id} aria-pressed={value===id} className={value===id?"selected":""} onClick={()=>onChange(id)}>{text}{value===id&&<Check size={14}/>}</button>)}</div></fieldset>;
}
function Toggle({title,note,value,onChange,icon}:{title:string;note:string;value:boolean;onChange:(v:boolean)=>void;icon:ReactNode}){
 return <div className="pn-toggle-row">{icon}<div><strong>{title}</strong><p>{note}</p></div><button className="pn-toggle" role="switch" aria-label={title} aria-checked={value} onClick={()=>onChange(!value)}><span/></button></div>;
}
function Sheet({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current,previous=document.activeElement as HTMLElement|null;d?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=overflow;d?.close();previous?.focus();};},[]);
 return <dialog ref={ref} className="pn-sheet" aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="pn-sheet-inner"><div className="pn-sheet-handle"/><header><h2>{title}</h2><button className="pn-icon" aria-label="Tutup" onClick={onClose}><X/></button></header>{children}</div></dialog>;
}
async function readImages(files:File[]){return Promise.all(files.map(file=>new Promise<string>((resolve,reject)=>{if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){reject(new Error("Pilih JPG, PNG atau WEBP, maksimum 5 MB setiap gambar."));return;}const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error("Gambar tidak dapat dibaca."));r.readAsDataURL(file);})));}
export function PawarnaGenerator({deployment="local"}:{deployment?:"local"|"cloud"}={}){
 const pwa=usePwa(),[screen,setScreen]=useState("home"),[selectedId,setSelectedId]=useState("");
 const [jobs,setJobs]=useState<PublicJob[]>([]),[products,setProducts]=useState<PublicProduct[]>([]),[usage,setUsage]=useState<Usage[]>([]),[ready,setReady]=useState<Ready|null>(null);
 const [step,setStep]=useState(0),[images,setImages]=useState<string[]>([]),[avatar,setAvatar]=useState(""),[productId,setProductId]=useState(""),[settings,setSettings]=useState<GenerationSettings>({...DEFAULT_SETTINGS}),[instructions,setInstructions]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[connection,setConnection]=useState(false),[sheet,setSheet]=useState<"repeat"|"corrections"|null>(null),[corrections,setCorrections]=useState(""),[projectView,setProjectView]=useState("");
 const [correctedName,setCorrectedName]=useState(""),[correctedCategory,setCorrectedCategory]=useState(""),[avatarSource,setAvatarSource]=useState("");
 const lock=useRef(false),request=useRef<{body:string;key:string}|null>(null),product=products.find(p=>p.id===productId),job=jobs.find(j=>j.id===selectedId);
 // Hash-only navigation shared with the Cloudflare Vite build, not Next page routing.
 // eslint-disable-next-line @next/next/no-location-assign-relative-destination
 function navigate(page:string,id?:string){window.location.assign("#"+(id?"video-"+id:page));}
 useEffect(()=>{const sync=()=>{const h=window.location.hash.slice(1);setScreen(h.startsWith("video-")?"result":h==="videos"?"projects":h==="app"?"profile":["home","create","projects","credits","profile"].includes(h)?h:"home");if(h.startsWith("video-"))setSelectedId(h.slice(6));window.scrollTo({top:0,behavior:"instant"});};queueMicrotask(sync);window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync);},[]);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const r=await fetch("/api/factory",{cache:"no-store",signal});if(!r.ok)throw new Error();const d=await r.json();setJobs(d.jobs);setProducts(d.products||[]);setUsage(d.usage||[]);setReady({...d.ready,paused:d.paused});setConnection(false);},[]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{if(!document.hidden&&navigator.onLine){try{await refresh(c.signal);}catch{if(!c.signal.aborted)setConnection(true);}}if(!c.signal.aborted)timer=setTimeout(poll,4000);};void poll();return()=>{c.abort();clearTimeout(timer);};},[refresh]);
 function change<K extends keyof GenerationSettings>(key:K,value:GenerationSettings[K]){setSettings(s=>{const n={...s,[key]:value};if(key==="videoStyle"&&!supportsCreator(String(value))&&n.subjectType.endsWith("_creator"))n.subjectType="auto";return n;});if(key==="videoStyle"&&!supportsCreator(String(value))||key==="subjectType"&&!String(value).endsWith("_creator"))setAvatar("");request.current=null;setError("");}
 async function post(url:string,body:unknown){const encoded=JSON.stringify(body);if(!request.current||request.current.body!==url+encoded)request.current={body:url+encoded,key:crypto.randomUUID()};const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":request.current.key},body:encoded});const d=await r.json();if(!r.ok)throw new Error(d.error||"Permintaan belum berjaya. Cuba lagi.");request.current=null;return d;}
 async function action(fn:()=>Promise<void>){if(lock.current)return;if(!navigator.onLine){setError("Sambung internet untuk meneruskan.");return;}lock.current=true;setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Sambungan terganggu. Cuba lagi dengan input sama.");}finally{lock.current=false;setBusy(false);}}
 function selectProduct(p:PublicProduct,at=1){setProductId(p.id);setImages([]);setAvatar("");setAvatarSource("");setSettings({...DEFAULT_SETTINGS,productId:p.id,videoStyle:recommendStyle(p.product?.category)});setInstructions("");setStep(p.stage==="ready"?at:0);request.current=null;setError("");navigate("create");}
 function newProduct(){setAvatarSource("");setProductId("");setImages([]);setAvatar("");setSettings({...DEFAULT_SETTINGS});setInstructions("");setStep(0);request.current=null;setError("");navigate("create");}
 async function upload(files:FileList|null,isAvatar=false){if(!files?.length)return;const chosen=Array.from(files);await action(async()=>{if(!isAvatar&&images.length+chosen.length>5)throw new Error("Maksimum 5 gambar produk.");const values=await readImages(chosen.slice(0,isAvatar?1:5));if(isAvatar)setAvatar(values[0]);else{setImages(old=>[...old,...values]);setProductId("");}request.current=null;});}
 async function analyse(){await action(async()=>{const d=await post("/api/products",{images,mode:"Auto",instructions:""});setProducts(old=>[d.product,...old.filter(p=>p.id!==d.product.id)]);setProductId(d.product.id);setSettings(s=>({...s,productId:d.product.id}));});}
 async function reuse(j:PublicJob,variation:"angle"|"style"|"random"|"edit"="edit"){await action(async()=>{
  let p=products.find(p=>p.id===j.settings?.productId);if(!p){const d=await post("/api/products",{source_job:j.id});p=d.product;setProducts(old=>[p!,...old.filter(item=>item.id!==p!.id)]);}
  const s={...(j.settings||DEFAULT_SETTINGS),productId:p!.id},aa=ANGLES.filter(a=>a[0]!=="auto"&&a[0]!==s.angle),ss=VIDEO_STYLES.filter(v=>v.id!==s.videoStyle);
  if(variation==="angle"||variation==="random")s.angle=aa[Math.floor(Math.random()*aa.length)][0];
  if(variation==="style"||variation==="random")s.videoStyle=ss[Math.floor(Math.random()*ss.length)].id;
  if(!supportsCreator(s.videoStyle)&&s.subjectType.endsWith("_creator"))s.subjectType="auto";
  setProductId(p!.id);setImages([]);setAvatar("");setAvatarSource(j.has_avatar&&s.subjectType.endsWith("_creator")?j.id:"");setSettings(s);setInstructions(variation==="style"&&j.plan?.angle?("Kekalkan angle terdahulu ini; ubah visual sahaja: "+j.plan.angle).slice(0,1000):"");setStep(p!.stage!=="ready"?0:variation==="edit"?1:4);setSheet(null);navigate("create");
 });}
 async function generate(){await action(async()=>{if(!product||product.stage!=="ready")throw new Error("Analisis produk belum siap.");const d=await post("/api/generate",{product_id:product.id,settings:{...settings,productId:product.id},instructions,avatar:avatar||undefined,avatar_source_job:!avatar&&settings.subjectType.endsWith("_creator")?avatarSource||undefined:undefined});setJobs(old=>[d.job,...old.filter(j=>j.id!==d.job.id)]);navigate("result",d.job.id);});}
 function next(){if(step===0&&product?.stage==="ready")change("videoStyle",recommendStyle(product.product?.category));setStep(s=>Math.min(4,s+1));window.scrollTo({top:0,behavior:"smooth"});}
 const videos=(items:PublicJob[])=>items.length?<div className="pn-video-grid">{items.map(j=><button key={j.id} className="pn-video-card" onClick={()=>navigate("result",j.id)}><div><img src={j.thumbnail_url} alt="" loading="lazy"/><span className={"pn-status "+j.stage}>{j.stage==="completed"?"Siap":j.stage==="failed"?"Perlu perhatian":"Dalam proses"}</span></div><strong>{j.product?.name||"Produk baru"}</strong><small>{styleName(j.settings?.videoStyle)} · 10s</small></button>)}</div>:<div className="pn-empty"><Clapperboard/><h3>Video pertama bermula di sini.</h3><p>Satu produk, banyak cara bercerita.</p><button className="pn-secondary" onClick={newProduct}>Buat video baru <Plus size={16}/></button></div>;
 const productCards=(items:PublicProduct[])=><div className="pn-product-list">{items.map(p=><button key={p.id} className="pn-product-card" onClick={()=>{setProjectView(p.id);navigate("projects");}}><img src={p.image_urls[0]} alt="" loading="lazy"/><div><strong>{p.product?.name||"Produk baru"}</strong><small>{p.stage==="ready"?jobs.filter(j=>(j.settings?.productId===p.id||j.id===p.source_job)).length+" video · Sedia untuk idea baru":p.stage==="failed"?"Analisis perlu perhatian":"Sedang kenal pasti produk…"}</small></div><ChevronRight size={18}/></button>)}</div>;
 const canGenerate=!!ready?.gemini&&ready.nexabot&&ready.worker&&!ready.paused&&pwa.online,viewed=products.find(p=>p.id===projectView);
 return <main className="pn-app"><header className="pn-header"><a href="#home" aria-label="Pawarna Home"><img src="/icons/icon-192.png" alt=""/><span>PAWARNA<small>STUDIO DALAM POKET</small></span></a><button className="pn-icon pn-profile-icon" aria-label="Profile" onClick={()=>navigate("profile")}><UserRound size={20}/></button></header><div className="pn-content">
 {!pwa.online&&<p className="pn-notice" role="status">Anda offline. Tiada permintaan baru dihantar.</p>}
 {connection&&<p className="pn-notice" role="status">Sambungan terganggu. Status akan dikemas kini apabila bersambung.</p>}
 {ready?.paused&&<details className="pn-pause"><summary><ShieldCheck size={15}/> Generation dijeda · draf masih boleh dibuat</summary><p>Semakan caj sedang dibuat. Tiada video baru atau retry berbayar automatik. Analisis produk masih menggunakan perkhidmatan AI.</p></details>}
 {pwa.waiting&&<div className="pn-notice">Versi baru tersedia. <button onClick={()=>{if(window.confirm("Kemas kini app? Draf belum dihantar akan hilang."))pwa.update();}}>Kemas kini</button></div>}
 {error&&<div className="pn-error" role="alert">{error}<button className="pn-icon" aria-label="Tutup ralat" onClick={()=>setError("")}><X size={16}/></button></div>}
 {!ready&&!connection&&<div className="pn-skeleton" aria-label="Memuatkan studio"/>}
 {screen==="home"&&<section className="pn-enter"><div className="pn-home-hero"><span className="pn-eyebrow"><Sparkles size={14}/> IDEA KECIL, KONTEN BARU</span><h1>Buat video affiliate<br/>dari <em>gambar produk.</em></h1><p>Kau pilih produk. Pawarna bantu susun idea, skrip dan visualnya.</p><button className="pn-primary" onClick={newProduct}>Buat Video Baru <Plus size={19}/></button><div className="pn-hero-foot"><span><Check size={13}/> 10 saat</span><span><Check size={13}/> Video menegak</span><span><Check size={13}/> Gaya kau</span></div><div className="pn-hero-art" aria-hidden="true"><div><Clapperboard size={36}/><span>produk → cerita</span></div><Sparkles size={30}/></div></div>
 {!!products.length&&<><div className="pn-section-title"><h2>Sambung Produk Terakhir</h2><a href="#projects">Semua <ChevronRight size={14}/></a></div>{productCards(products.slice(0,2))}</>}
 <div className="pn-section-title"><h2>Video Terbaru</h2><a href="#projects">Lihat semua <ChevronRight size={14}/></a></div>{videos(jobs.slice(0,4))}<div className="pn-tip"><Lightbulb size={20}/><p><strong>Label jelas, hasil lebih tepat.</strong><br/>Ambil gambar depan produk dengan cahaya yang baik.</p></div></section>}
 {screen==="create"&&<section className="pn-enter"><div className="pn-title-row"><button className="pn-icon" aria-label="Kembali" onClick={()=>step?setStep(step-1):navigate("home")}><ArrowLeft size={21}/></button><div><span className="pn-eyebrow">VIDEO BARU</span><h1>{flow[step]}</h1></div><span className="pn-step-count">{step+1} / 5</span></div><ol className="pn-stepper" aria-label="Langkah cipta video">{flow.map((f,i)=><li key={f} className={i<=step?"active":""} aria-current={i===step?"step":undefined}><span>{i<step?<Check size={12}/>:i+1}</span><small>{f}</small></li>)}</ol><div key={step} className="pn-step-body pn-enter">
 {step===0&&<><h2>Kenalkan produk kau.</h2><p className="pn-muted">Upload 1–5 gambar. AI akan baca label dan semak maklumat yang boleh disahkan.</p>{!productId&&<label className="pn-upload"><input type="file" aria-label="Upload gambar produk" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||images.length>=5} onChange={e=>{void upload(e.target.files);e.target.value="";}}/><span><ImagePlus size={28}/></span><strong>{images.length?"Tambah gambar produk":"Pilih gambar produk"}</strong><small>JPG, PNG, WEBP · 5 MB / gambar · 12 MB jumlah</small></label>}
 <div className="pn-thumbs">{(product?.image_urls||images).map((src,i)=><div key={src}><img src={src} alt={"Produk "+(i+1)}/>{!productId&&<button className="pn-icon" aria-label={"Buang gambar "+(i+1)} onClick={()=>{setImages(images.filter((_,n)=>n!==i));request.current=null;}}><X size={14}/></button>}</div>)}</div>
 {product&&<div className="pn-card">{product.stage==="ready"?<><span className="pn-tag"><Check size={13}/> Produk dikenal pasti</span><h3>{product.product?.name}</h3><p>{product.product?.category}</p><p className="pn-muted">{product.product?.description}</p><ul className="pn-features">{product.product?.observed_features.slice(0,4).map(f=><li key={f}>{f}</li>)}</ul><dl className="pn-product-facts"><div><dt>Fungsi utama</dt><dd>{product.product?.primary_function||"Belum disahkan"}</dd></div><div><dt>Sasaran pengguna</dt><dd>{product.product?.target_audience||"Belum disahkan"}</dd></div></dl>{product.product?.uncertainty&&<p className="pn-notice">{product.product.uncertainty}</p>}<span className="pn-tag neutral">{product.research?.status==="grounded"?"Sumber web ditemui · padanan disemak":"Maklumat web belum disahkan"}</span>{product.corrections&&<p className="pn-muted">Pembetulan kau (belum disahkan): {product.corrections}</p>}<ResearchSources research={product.research}/><button className="pn-text" onClick={()=>{setCorrections(product.corrections||"");setCorrectedName(product.product?.name||"");setCorrectedCategory(product.product?.category||"");setSheet("corrections");}}>Betulkan Maklumat <Pencil size={14}/></button></>:product.stage==="failed"?<><h3>Analisis belum siap</h3><p>{product.error}</p><button className="pn-secondary" onClick={newProduct}>Pilih gambar semula</button></>:<div className="pn-working" role="status"><LoaderCircle className="pn-spin"/><h3>{product.stage==="researching"?"Sedang semak sumber…":"Sedang kenal pasti produk…"}</h3><p>Belum ada video berbayar dihantar.</p><div className="pn-skeleton"/></div>}</div>}
 {!productId&&<p className="pn-footnote">Analisis menggunakan AI. Generation video hanya selepas semakan akhir kau.</p>}{product?.stage==="ready"&&<button className="pn-text" onClick={newProduct}>Guna produk lain</button>}</>}
 {step===1&&<><h2>Macam mana nak bercerita?</h2><p className="pn-muted">Pilih satu gaya. Setiap gaya mengubah susunan visual video.</p><div className="pn-style-grid">{[...VIDEO_STYLES].sort((a,b)=>Number(b.id===recommendStyle(product?.product?.category))-Number(a.id===recommendStyle(product?.product?.category))).map(v=>{const Icon=styleIcons[VIDEO_STYLES.findIndex(s=>s.id===v.id)];return <button key={v.id} className={"pn-style-card "+(settings.videoStyle===v.id?"selected":"")} aria-pressed={settings.videoStyle===v.id} onClick={()=>change("videoStyle",v.id)}><div className={"pn-style-art art-"+v.id}><Icon size={32}/><span className="pn-select-dot">{settings.videoStyle===v.id&&<Check size={12}/>}</span></div><strong>{v.label}</strong><small>{v.note}</small>{v.id===recommendStyle(product?.product?.category)&&<span className="pn-recommended"><Sparkles size={11}/> AI Recommended</span>}</button>;})}</div><p className="pn-footnote">Cadangan gaya berdasarkan kategori hasil analisis produk.</p></>}
 {step===2&&<><h2>Mulakan dari sudut apa?</h2><p className="pn-muted">Style ialah rupa video. Angle ialah cara kau tarik perhatian.</p><Choices label="Sales angle" value={settings.angle} items={ANGLES.map(a=>[a[0],a[1]] as const)} onChange={v=>change("angle",v as GenerationSettings["angle"])}/><div className="pn-angle-preview"><Lightbulb size={26}/><h3>{settings.angle==="auto"?"Biar Pawarna pilih yang sesuai.":angleName(settings.angle)}</h3><p>Hook dan skrip ikut angle ini, menggunakan fakta produk yang boleh disokong. Tiada janji hasil atau testimoni rekaan.</p></div></>}
 {step===3&&<><h2>Biar kena dengan gaya kau.</h2><p className="pn-muted">Suara, subjek dan pakaian. Semua di satu tempat.</p><div className="pn-card"><Toggle icon={settings.voiceoverEnabled?<Mic/>:<VolumeX/>} title="Voiceover" note={settings.voiceoverEnabled?"Suara Melayu untuk bercerita.":"Visual sahaja, tanpa dialog."} value={settings.voiceoverEnabled} onChange={v=>change("voiceoverEnabled",v)}/>{settings.voiceoverEnabled&&<><Choices label="Suara" value={settings.voiceGender} items={[["auto","Auto"],["female","Perempuan Melayu"],["male","Lelaki Melayu"]]} onChange={v=>change("voiceGender",v as GenerationSettings["voiceGender"])}/><Choices label="Cara bercakap" value={settings.voiceStyle} items={[["natural","Natural"],["energetic","Energetic"],["soft_sell","Soft Sell"],["direct","Direct"]]} onChange={v=>change("voiceStyle",v as GenerationSettings["voiceStyle"])}/></>}</div>
 <div className="pn-card"><Choices label="Subjek visual" value={settings.subjectType} items={[["auto","Auto"],["female_hands","Tangan perempuan"],["male_hands","Tangan lelaki"],["no_hands","Tanpa tangan"],...(supportsCreator(settings.videoStyle)?[["female_creator","Creator perempuan"],["male_creator","Creator lelaki"]] as [string,string][]:[])]} onChange={v=>change("subjectType",v as GenerationSettings["subjectType"])}/><p className="pn-footnote">{supportsCreator(settings.videoStyle)?"Creator penuh tersedia untuk gaya ini.":"Gaya ini fokus produk; creator penuh tidak digunakan."} Grip dan skala produk diarahkan supaya natural.</p>{settings.subjectType.endsWith("_creator")&&<><label className="pn-avatar-upload"><UserRound size={19}/><span>{avatar?"Tukar avatar":"Tambah avatar (pilihan)"}</span><input type="file" aria-label="Upload avatar pilihan" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files,true);e.target.value="";}}/><Plus size={16}/></label>{avatarSource&&!avatar&&<p className="pn-footnote">Avatar daripada video terdahulu akan digunakan. <button className="pn-text" onClick={()=>setAvatarSource("")}>Buang avatar</button></p>}{avatar&&<div className="pn-avatar"><img src={avatar} alt="Avatar pilihan"/><p>Wajah sebagai rujukan.<br/>Pakaian ikut tetapan.</p><button className="pn-icon" aria-label="Buang avatar" onClick={()=>setAvatar("")}><X size={17}/></button></div>}</>}</div>
 <div className="pn-card"><Toggle icon={<ShieldCheck/>} title="Shariah Compliance" note="Kawalan pakaian, aurat dan suasana." value={settings.shariahCompliance} onChange={v=>setSettings(s=>({...s,shariahCompliance:v,auratLevel:v?"full":null}))}/>{settings.shariahCompliance&&<Choices label="Liputan aurat" value={settings.auratLevel||"full"} items={[["standard","Standard"],["full","Full Coverage"]]} onChange={v=>change("auratLevel",v as "standard"|"full")}/>}<p className="pn-footnote">{settings.shariahCompliance?"Pakaian longgar dan tidak jarang. Full Coverage menambah liputan penuh, lengan hingga pergelangan serta hijab untuk creator perempuan.":"Arahan khusus Shariah dan aurat tidak ditambah."}</p></div><p className="pn-footnote">Pilihan suara dan pematuhan mengarah hasil AI, bukan jaminan. Semak video sebelum diterbitkan.</p></>}
 {step===4&&<><h2>Semak. Lepas tu, cipta.</h2><p className="pn-muted">Satu video pendek, dengan pilihan kau.</p><div className="pn-review-product">{product?.image_urls[0]&&<img src={product.image_urls[0]} alt="Produk pilihan"/>}<div><span className="pn-eyebrow">PRODUK KAU</span><h3>{product?.product?.name||"Produk"}</h3><small>{product?.product?.category}</small></div></div><dl className="pn-review-list">{[["Style",styleName(settings.videoStyle)],["Angle",angleName(settings.angle)],["Suara",voiceName(settings)],["Visual",subjectName(settings.subjectType)+(avatar||avatarSource&&settings.subjectType.endsWith("_creator")?" · Avatar sendiri":"")],["Shariah",settings.shariahCompliance?"ON · "+(settings.auratLevel==="full"?"Full Coverage":"Standard"):"OFF"],["Format","10 saat · 9:16"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><label className="pn-field">Arahan tambahan <span className="pn-muted">(pilihan)</span><textarea value={instructions} maxLength={1000} onChange={e=>setInstructions(e.target.value)} placeholder="Contoh: Fokus pada label. Jangan sebut harga."/></label><div className="pn-notice">1 permintaan video: 0.5 kredit penyedia. Tiada retry berbayar automatik. Caj bersih atau refund perlu disemak dengan penyedia.</div><button className="pn-text" onClick={()=>setStep(1)}>Edit pilihan <Pencil size={15}/></button></>}
 </div><div className="pn-create-footer"><span>{step===4?"10 saat · Satu permintaan video":"Langkah "+(step+1)+" daripada 5"}</span><button className="pn-primary" disabled={busy||!pwa.online||(step===0?productId?product?.stage!=="ready":!images.length:step===4?!canGenerate:false)} onClick={()=>step===0&&!productId?void analyse():step===4?void generate():next()}>{busy?<LoaderCircle size={18} className="pn-spin"/>:step===4?<Sparkles size={18}/>:null}{busy?"Sebentar…":step===0&&!productId?"Kenal Pasti Produk":step===4?ready?.paused?"Generation Dijeda":"Generate Video":"Teruskan"}{!busy&&step<4&&<ArrowRight size={18}/>}</button></div></section>}
 {screen==="projects"&&<section className="pn-enter"><div className="pn-section-title"><div><span className="pn-eyebrow">KOLEKSI KAU</span><h1>{viewed?viewed.product?.name||"Projek produk":"Projects"}</h1></div>{viewed?<button className="pn-icon" aria-label="Semua projek" onClick={()=>setProjectView("")}><ArrowLeft/></button>:<button className="pn-icon" aria-label="Produk baru" onClick={newProduct}><Plus/></button>}</div>{viewed?<><div className="pn-thumbs">{viewed.image_urls.map(src=><div key={src}><img src={src} alt="Gambar produk"/></div>)}</div><p>{viewed.product?.description}</p><p className="pn-muted">{viewed.research?.status==="grounded"?"Sumber web disimpan bersama produk.":"Maklumat web belum disahkan."}</p><button className="pn-primary" onClick={()=>selectProduct(viewed)}>Video Baru <Plus size={18}/></button><div className="pn-used"><small>Style digunakan</small><p>{[...new Set(jobs.filter(j=>(j.settings?.productId===viewed.id||j.id===viewed.source_job)).map(j=>styleName(j.settings?.videoStyle)))].join(" · ")||"Belum ada"}</p><small>Angle digunakan</small><p>{[...new Set(jobs.filter(j=>(j.settings?.productId===viewed.id||j.id===viewed.source_job)).map(j=>angleName(j.settings?.angle)))].join(" · ")||"Belum ada"}</p></div><div className="pn-section-title"><h2>Video produk ini</h2></div>{videos(jobs.filter(j=>(j.settings?.productId===viewed.id||j.id===viewed.source_job)))}</>:<><p className="pn-muted">Gambar dan analisis disimpan. Buka produk untuk idea seterusnya.</p>{products.length?productCards(products):<div className="pn-empty"><FolderHeart/><h3>Rumah untuk produk kau.</h3><p>Simpan produk pertama dengan analisis gambar.</p><button className="pn-secondary" onClick={newProduct}>Tambah produk <Plus size={16}/></button></div>}<div className="pn-section-title"><h2>Semua video</h2><span>{jobs.length}</span></div>{videos(jobs)}</>}</section>}
 {screen==="result"&&<section className="pn-enter">{job?<><button className="pn-text" onClick={()=>navigate("projects")}><ArrowLeft size={17}/> Projects</button><div className="pn-section-title"><h1>{job.product?.name||"Video kau"}</h1></div><div className="pn-result-grid"><div className="pn-player">{job.video_url?<video src={job.video_url} controls playsInline preload="metadata"/>:<><img src={job.thumbnail_url} alt="Gambar rujukan, bukan video siap"/><div>{job.stage==="failed"?<X size={28}/>:<LoaderCircle size={28} className="pn-spin"/>}<strong>{STAGES[job.stage]}</strong><small>Gambar rujukan · video belum tersedia</small></div></>}</div><div><p className={job.stage==="failed"?"pn-notice":"pn-muted"} role="status">{job.error||STAGES[job.stage]}</p>{!done(job)&&<ol className="pn-progress">{[["analysing","Kenal pasti produk"],["researching","Semak sumber"],["planning","Susun angle, suara & visual"],["processing","Jana video"],["saving","Kemasan & simpan"]].map(([id,label])=><li key={id} className={job.stage===id||id==="processing"&&job.stage==="submitting"?"current":""}>{label}</li>)}</ol>}{job.plan&&<div className="pn-card"><span className="pn-tag">{styleName(job.settings?.videoStyle)}</span><h3>{job.plan.angle}</h3><p>{job.settings?.voiceoverEnabled===false?"Visual sahaja — tiada voiceover.":job.plan.script}</p></div>}{job.video_url&&<a className="pn-primary" href={job.video_url+"?download=1"}><Download size={18}/> Download Video</a>}{done(job)&&<><div className="pn-result-actions"><button className="pn-secondary" disabled={busy} onClick={()=>setSheet("repeat")}><RefreshCw size={16}/> Generate Lagi</button><button className="pn-secondary" disabled={busy} onClick={()=>void reuse(job,"angle")}><Sparkles size={16}/> Angle Lain</button></div><button className="pn-text" disabled={busy} onClick={()=>void reuse(job)}>Guna Produk Sama <ArrowRight size={15}/></button><p className="pn-footnote">Semak pilihan dahulu. Butang ini tidak terus menjana video.</p></>}<ResearchSources research={job.research}/><details className="pn-support"><summary>Info job & bantuan</summary><JobDiagnostics job={job} deployment={deployment}/></details></div></div></>:<div className="pn-empty"><p>{ready?"Video tidak ditemui dalam sesi ini.":"Memuatkan video…"}</p><a href="#projects">Buka Projects</a></div>}</section>}
 {screen==="credits"&&<section className="pn-enter"><span className="pn-eyebrow">TELUS TENTANG PENGGUNAAN</span><h1>Credits</h1><div className="pn-credit-card"><Wallet size={28}/><small>Anggaran permintaan direkodkan</small><strong>{usage.reduce((sum,u)=>sum+u.recorded_cost,0).toFixed(1)} <span>kredit</span></strong><p>{usage.reduce((sum,u)=>sum+u.attempts,0)} permintaan · sejarah sesi ini</p></div><p className="pn-notice">Ini bukan baki akaun atau caj bersih. Refund belum disahkan. Rekod ini terhad kepada video dalam sesi ini; semak transaksi penyedia untuk angka sebenar.</p><div className="pn-section-title"><h2>Rekod video</h2></div>{usage.length?usage.map(u=><button className="pn-ledger" key={u.id} onClick={()=>navigate("result",u.id)}><div><strong>{u.name}</strong><small>{u.attempts} permintaan · {u.stage==="failed"?"Gagal · refund belum disahkan":u.stage==="completed"?"Siap":"Dalam proses"}</small></div><span>{u.recorded_cost.toFixed(1)}</span></button>):<p className="pn-muted">Belum ada permintaan direkodkan dalam sesi ini.</p>}</section>}
 {screen==="profile"&&<section className="pn-enter"><span className="pn-eyebrow">RUANG KAU</span><h1>Profile</h1><div className="pn-profile-card"><img src="/icons/icon-192.png" alt="Pawarna"/><h2>Studio, ikut kau.</h2><p>Buka terus dari home screen. Lebih dekat dengan idea seterusnya.</p>{pwa.installed?<span className="pn-tag"><Check size={14}/> App sudah dipasang</span>:pwa.canInstall?<button className="pn-primary" onClick={()=>void pwa.install()}><Smartphone size={18}/> Pasang Pawarna</button>:<p className="pn-notice">{pwa.ios?"Safari → Share → Add to Home Screen.":"Buka menu browser dan pilih Install app atau Add to Home Screen jika tersedia."}</p>}</div><div className="pn-card"><h3>Sesi peribadi pada peranti ini</h3><p className="pn-muted">Belum ada akaun atau sync antara peranti. Jangan padam data browser jika mahu kekalkan akses kepada projek. Link yang tidak diketahui orang bukan perlindungan akses.</p></div><div className="pn-card"><h3>Tetapan studio</h3><p>10 saat · Video menegak · Bahasa Melayu</p><p className="pn-muted">Suara tersuai dan dialek tambahan belum tersedia. Avatar pilihan tersedia untuk gaya creator penuh.</p><p className="pn-footnote">Semak fakta produk, anatomi, suara dan pakaian sebelum berkongsi hasil AI.</p></div></section>}
 </div><nav className="pn-bottom-nav" aria-label="Navigasi utama">{[["home","Home",Home],["projects","Projects",FolderHeart],["create","Create",Plus],["credits","Credits",Wallet],["profile","Profile",UserRound]].map(([id,label,Icon])=>{const I=Icon as typeof Home;return <button key={String(id)} className={(screen===id||screen==="result"&&id==="projects"?"active ":"")+(id==="create"?"pn-create-tab":"")} aria-current={screen===id?"page":undefined} onClick={()=>navigate(String(id))}><span><I size={21}/></span><small>{String(label)}</small></button>;})}</nav>
 {sheet==="repeat"&&job&&<Sheet title="Idea seterusnya?" onClose={()=>setSheet(null)}>{error&&<p className="pn-error" role="alert">{error}</p>}<p className="pn-muted">Guna produk sama. Pilih variasi, kemudian semak sebelum generate.</p>{[["angle","Style sama, angle baru","Ubah cara tarik perhatian."],["style","Angle sama, style baru","Cerita sama, visual lain."],["random","Versi rawak","Angle dan style yang berbeza."],["edit","Edit sendiri","Pilih semula semua kawalan."]].map(([id,title,note])=><button disabled={busy} className="pn-sheet-option" key={id} onClick={()=>void reuse(job,id as "angle"|"style"|"random"|"edit")}><div><strong>{title}</strong><small>{note}</small></div><ChevronRight size={18}/></button>)}</Sheet>}
 {sheet==="corrections"&&product&&<Sheet title="Betulkan maklumat" onClose={()=>setSheet(null)}>{error&&<p className="pn-error" role="alert">{error}</p>}<p className="pn-muted">Nyatakan nama, kategori atau pembetulan label. Disimpan sebagai nota kau, bukan bukti web yang disahkan.</p><label className="pn-field">Nama produk<input value={correctedName} maxLength={160} onChange={e=>setCorrectedName(e.target.value)}/></label><label className="pn-field">Kategori<input value={correctedCategory} maxLength={160} onChange={e=>setCorrectedCategory(e.target.value)}/></label><label className="pn-field">Nota pembetulan<textarea value={corrections} maxLength={1000} onChange={e=>setCorrections(e.target.value)} placeholder="Contoh: Nama pada label ialah…"/></label><button disabled={busy} className="pn-primary" onClick={()=>void action(async()=>{const d=await post("/api/products/"+product.id+"/corrections",{corrections,name:correctedName,category:correctedCategory});setProducts(old=>old.map(p=>p.id===product.id?d.product:p));setSheet(null);})}>Simpan Pembetulan <Check size={17}/></button></Sheet>}
 </main>;
}
